### ISSUE TITLE
Badge is placed above modal backdrop

### ISSUE THREAD

**Issue by paustint** [Wikiki/bulma-badge#5]
When using this badge in combination with a modal, the badge has a higher z-index than the modal backdrop.

If the badge was on a modal component, this might be required, but if the badge is somewhere on the body (which is the most likely) then it appears to glow compared to the rest of the document.

**Note**: z-index of the modal is 20

I fixed by moving the z-index to another class. I am sure you know a lot more about Bulma's inner workings than I do, so this might be a naive approach :)

```css
.badge[data-badge]::after {
  position: absolute;
  left: 100%;
  margin: 0;
  background: #00d1b2;
  background-clip: padding-box;
  border-radius: 1rem;
  box-shadow: 0 0 0 0.1rem white;
  color: white;
  content: attr(data-badge);
  display: inline-block;
}

.badge.is-badge-above-modal[data-badge]::after {
  z-index: 99;
}
```

![weekly](https://user-images.githubusercontent.com/5461649/34457937-e48463c0-ed7d-11e7-8665-5abce6c274e1.png)
